#!/bin/bash

# Header for the fstab output
echo "# /etc/fstab: static file system information."
echo "# Generated by script"

# Loop through each mounted file system
while read -r line; do
    fs_spec=$(echo "$line" | cut -d ' ' -f 1) # File system source
    fs_file=$(echo "$line" | cut -d ' ' -f 2) # Mount point
    fs_vfstype=$(echo "$line" | cut -d ' ' -f 3) # File system type
    fs_mntops=$(echo "$line" | cut -d ' ' -f 4) # Mount options

    # Filter out non-permanent file systems
    case "$fs_spec" in
        proc|sysfs|devtmpfs|devpts|tmpfs|securityfs|cgroup|pstore|udev|tracefs|none|cgroup2|sunrpc|nfsd|efivarfs|systemd-1|binfmt_misc|autofs|configfs|mqueue|debugfs|hugetlbfs|rpc_pipefs|fusectl|nsfs|/dev/loop*|squashfs)
            continue
            ;;
    esac

    # Getting UUID for the filesystem
    uuid=$(blkid -s UUID -o value "$fs_spec" 2>/dev/null)
    if [ -n "$uuid" ]; then
        fs_spec="UUID=$uuid"
    fi

    # Write to the standard output
    echo "$fs_spec $fs_file $fs_vfstype $fs_mntops 0 0"
done < /proc/mounts
